config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  resources :productions

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/production.rb
class Production < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/productions_controller.rb
class ProductionsController < ApplicationController
  def new
    @production= Production.new
  end

  def create
    @production = Production.new(production_params)
    if @production.save
      redirect_to productions_path
    else
      render :new
    end

  end

  def index
    @productions = Production.page(params[:page]).reverse_order
  end

  def edit
    @production = Production.find(params[:id])
  end

  def update
    @production = Production.find(params[:id])
    if @production.update(production_params)
      redirect_to productions_path
    else
      render :edit
    end
  end

  def destroy
    @production = Production.find(params[:id])
    @production.destroy
    redirect_to productions_path
  end

  private

  def production_params
    params.require(:production).permit(:ordernumber, :customer, :product, :ruler, :platform, :progress)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/productions_helper.rb
module ProductionsHelper
end

app/views/homes/top.html.erb
<div class="summary">
  <div>
    <h4 style="padding: 100px;">このサイトは工場用の生産管理や在庫管理です</h4>
  </div>
  <div>
    <%= link_to "表示する", productions_path, class: "btn" %>
  </div>
</div>

app/views/inventories/index.html.erb
<div style="width: 100%;">
  <div class="new">
  <%= link_to "登録", new_inventory_path %>
  </div>
  <table style="margin: 0 auto; border-bottom: solid 1px #000s;">
    <thead style="border-bottom: solid 1px #000;">
      <tr>
        <th class="tablehead">受注番号/板厚</th>
        <th class="tablehead">顧客/板材</th>
        <th class="tablehead">製品名/定尺</th>
        <th class="tablehead">台数/枚数</th>
        <th class="tablehead">進捗状況/在庫状況</th>
      </tr>
    </thead>
    <tbody>
      <% @inventories.each do |invento| %>
      <tr>
        <td><%= invento.ordernumber %></td>
        <td><%= invento.customer %></td>
        <td>
          <% if invento.product %>
            <%= invento.product %>
          <% else %>
            <%= invento.ruler %>
          <% end %>
        </td>
        <td><%= invento.platform %></td>
        <td><%= invento.progress %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/inventories/new.html.erb
<div style="width: 500px; margin: 0 auto;">

  <div class="mb-5" style="text-align: center">
    <input type="radio" name="product" value="生産管理" id="p1" checked/>生産管理
    <span style="padding-left: 25px;"><input type="radio" name="product" value="在庫管理" id="p2"/>在庫管理</span>
  </div>


  <%= form_with model: @inventory, local:true do |f| %>
  <table>
    <tbody id="production">

      <tr>
        <td>注文番号</td>
        <td><%= f.text_field :ordernumber %></td>
      </tr>

      <tr>
        <td>顧客</td>
        <td><%= f.text_field :customer %></td>
      </tr>

      <tr>
        <td>製品名</td>
        <td><%= f.text_field :product %></td>
      </tr>

      <tr>
        <td>台数</td>
        <td><%= f.text_field :platform %></td>
      </tr>

      <tr>
        <td>進捗状況</td>
        <td><%= f.text_field :progress %></td>
      </tr>

    </tbody>
  </table>
  <% end %>

  <%= form_with model: @invento, local:true do |f| %>
  <table>
    <tbody id="management">

      <tr>
        <td>板厚</td>
        <td><%= f.text_field :ordernumber %></td>
      </tr>

      <tr>
        <td>材質</td>
        <td><%= f.text_field :customer %></td>
      </tr>

      <tr>
        <td>定尺</td>
        <td><%= f.text_field :ruler %></td>
      </tr>

      <tr>
        <td>枚数</td>
        <td><%= f.text_field :platform %></td>
      </tr>

      <tr>
        <td>在庫状況</td>
        <td><%= f.text_field :progress %></td>
      </tr>

    </tbody>
  </table>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inventory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <div class="logo">
      <%= link_to "Inventory", root_path, class: "title" %>
    </div>
    <nav>
      <ul>
        <li><%= link_to "top", root_path, class: "side" %></li>
        <li><%= link_to "一覧", productions_path, class: "side" %></li>
      </ul>
    </nav>
  </header>
  <body>
    <%= yield %>
  </body>
</html>

app/views/productions/edit.html.erb
<div class="new-form">
  <div style="width: 500px; margin: 0px auto; padding-top: 50px;">

  <% if @production.product %>
    <%= form_with model: @production, local:true do |f| %>
    <table>
      <tbody>

        <tr>
          <td class="tn">注文番号</td>
          <td><%= f.text_field :ordernumber, class: "tf" %></td>
        </tr>

        <tr>
          <td class="tn">顧客</td>
          <td><%= f.text_field :customer, class: "tf" %></td>
        </tr>

        <tr>
          <td class="tn">製品名</td>
          <td><%= f.text_field :product, class: "tf" %></td>
        </tr>

        <tr>
          <td class="tn">台数</td>
          <td><%= f.text_field :platform, class: "tf" %></td>
        </tr>

        <tr>
          <td class="tn">進捗状況</td>
          <td><%= f.text_field :progress, class: "tf" %></td>
        </tr>

        <tr>
          <td></td>
          <td><button class="bt" type="submit">変更を保存</button></td>
        </tr>

      </tbody>
    </table>
    <% end %>
  <% else %>
    <%= form_with model: @production, local:true do |f| %>
    <table>
      <tbody>

        <tr>
          <td class="tn">板厚</td>
          <td><%= f.text_field :ordernumber, class: "tf" %></td>
        </tr>

        <tr>
          <td class="tn">材質</td>
          <td><%= f.text_field :customer, class: "tf" %></td>
        </tr>

        <tr>
          <td class="tn">定尺</td>
          <td><%= f.text_field :ruler, class: "tf" %></td>
        </tr>

        <tr>
          <td class="tn">枚数</td>
          <td><%= f.text_field :platform, class: "tf" %></td>
        </tr>

        <tr>
          <td class="tn">在庫状況</td>
          <td><%= f.text_field :progress, class: "tf" %></td>
        </tr>

        <tr>
          <td></td>
          <td><button class="bt" type="submit">変更を保存</button></td>
        </tr>

      </tbody>
    </table>
    <% end %>
  <% end %>
  </div>
</div>

app/views/productions/index.html.erb
<div class="index-invento">
  <div style="width: 100%;">
    <div class="new">
    <%= link_to "登録", new_production_path, class: "btn-new" %>
    </div>
    <table style="margin: 0 auto; border-bottom: solid 1px #000s;">
      <thead style="border-bottom: solid 1px #000;">
        <tr>
          <th class="tablehead">受注番号/板厚(t)</th>
          <th class="tablehead">顧客/板材</th>
          <th class="tablehead">製品名/定尺</th>
          <th class="tablehead">台数/枚数</th>
          <th class="tablehead">進捗状況/在庫状況</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @productions.each do |pro| %>
        <tr>
          <td class="tablehead"><%= pro.ordernumber %></td>
          <td class="tablehead"><%= pro.customer %></td>
          <td class="tablehead">
            <% if pro.product %>
              <%= pro.product %>
            <% else %>
              <%= pro.ruler %>
            <% end %>
          </td>
          <td class="tablehead"><%= pro.platform %></td>
          <td class="tablehead"><%= pro.progress %></td>
          <td><%= link_to "編集", edit_production_path(pro.id), class: "btn" %></td>
          <td><%= link_to "削除", production_path(pro.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn-delete" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @productions %>

  </div>
</div>

app/views/productions/new.html.erb
<div class="new-form">
  <div style="width: 500px; margin: 0 auto;">

    <div style="padding-top: 50px; text-align: center">
      <input type="radio" name="product" value="生産管理" id="p1" checked/>生産管理
      <span style="padding-left: 25px;"><input type="radio" name="product" value="在庫管理" id="p2"/>在庫管理</span>
    </div>


    <%= form_with model: @production, local:true do |f| %>
    <table>
      <tbody id="pro">

        <tr>
          <td class="tn">注文番号</td>
          <td><%= f.text_field :ordernumber, class: "tf" %></td>
        </tr>

        <tr>
          <td class="tn">顧客</td>
          <td><%= f.text_field :customer, class: "tf" %></td>
        </tr>

        <tr>
          <td class="tn">製品名</td>
          <td><%= f.text_field :product, class: "tf" %></td>
        </tr>

        <tr>
          <td class="tn">台数</td>
          <td><%= f.text_field :platform, class: "tf" %></td>
        </tr>

        <tr>
          <td class="tn">進捗状況</td>
          <td><%= f.text_field :progress, class: "tf" %></td>
        </tr>

        <tr>
          <td></td>
          <td><button class="bt" type="submit">新規投稿</button></td>
        </tr>

      </tbody>
    </table>
    <% end %>
    <%= form_with model: @production, local:true do |f| %>
    <table>
      <tbody id="man">

        <tr>
          <td class="tn">板厚</td>
          <td><%= f.text_field :ordernumber, class: "tf" %></td>
        </tr>

        <tr>
          <td class="tn">材質</td>
          <td><%= f.text_field :customer, class: "tf" %></td>
        </tr>

        <tr>
          <td class="tn">定尺</td>
          <td><%= f.text_field :ruler, class: "tf" %></td>
        </tr>

        <tr>
          <td class="tn">枚数</td>
          <td><%= f.text_field :platform, class: "tf" %></td>
        </tr>

        <tr>
          <td class="tn">在庫状況</td>
          <td><%= f.text_field :progress, class: "tf" %></td>
        </tr>

        <tr>
          <td></td>
          <td><button class="bt" type="submit">新規投稿</button></td>
        </tr>

      </tbody>
    </table>
    <% end %>
  </div>
</div>